# Generated by Django 4.1.5 on 2023-03-15 09:37

import django.contrib.auth.base_user
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='only numbers are allowed', regex='^([1-9][0-9]{9})$')])),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('roll_no', models.CharField(max_length=100, unique=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'highereducation'), (2, 'placed'), (3, 'Other')], null=True)),
                ('firm', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='alumnipage/images/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, django.contrib.auth.base_user.BaseUserManager),
        ),
    ]
